version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_dockerizing
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: TqF7dbvsG
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - notes_network
  notes_app:
    container_name: notes_app_dockerizing
    build: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432  
    networks:
      - notes_network

volumes:
  database_dockerizing:
  api_volume:

networks:
  notes_network:
    driver: bridge